const diaries = [
	{
		id: "6ffwr32bqfa",
		title: "Thanksgiving Dinner",
		about: "This article is about the holiday in general. For the specific national holidays",
		content: `<h1>Thanksgiving</h1> <blockquote> This article is about the holiday in general. For the specific national holidays, see Thanksgiving (Canada) and Thanksgiving (United States). For other uses, see Thanksgiving (disambiguation). "Turkey Day" redirects here. For the Turkish Republic Day, see Republic Day (Turkey). </blockquote> <img src="https://wallpapercave.com/uwp/uwp906066.jpeg" alt="wallpapercave" /> <p> Thanksgiving is a national holiday celebrated on various dates in the United States, Canada, Grenada, Saint Lucia, and Liberia. It began as a day of giving thanks for the blessing of the harvest and of the preceding year. Similarly named festival holidays occur in Germany and Japan. Thanksgiving is celebrated on the second Monday of October in Canada and on the fourth Thursday of November in the United States and around the same part of the year in other places. Although Thanksgiving has historical roots in religious and cultural traditions, it has long been celebrated as a secular holiday as well. </p> <h3>Countries it is celebrated in: </h3> <ul> <li>Canada</li> <li>Unites States</li> <li>Australia</li> <li>Brazil</li> </ul> <table> <thead> <tr> <th>S. No.</th> <th>Name</th> <th>Title</th> </tr> </thead> <tbody> <tr> <td>20107</td> <td>Akshat Mittal</td> <td>MERN Stack Developer</td> </tr> <tr> <td>20106</td> <td>Akshat Khosya</td> <td>MERN Stack Developer</td> </tr> </tbody> </table>`,
		cover: "https://wallpapercave.com/uwp/uwp903093.jpeg",
		color: "#c15b1d",
		time: new Date(2018, 11, 24, 10, 33, 30),
	},
	{
		id: "aldh32bd929",
		title: "Development",
		about: "This is a blog about MERN Stack Development",
		content: `<h1>Development</h1> <blockquote> <cite> Website without visitors is like a ship lost in the horizon. </cite> </blockquote> <img src="https://cdn.pixabay.com/photo/2018/08/18/13/26/interface-3614766__340.png" alt="wallpapercave" /> <p> A front-end dev takes care of layout, design and interactivity using HTML, CSS and JavaScript. They take an idea from the drawing board and turn it into reality. What you see and what you use, such as the visual aspect of the website, the drop down menus and the text, are all brought together by the front-end dev, who writes a series of programmes to bind and structure the elements, make them look good and add interactivity. </p> <h3>Browsers: </h3> <p> These programmes are run through a browser. The backend developer engineers what is going on behind the scenes. This is where the data is stored, and without this data, there would be no frontend. The backend of the web consists of the server that hosts the website, an application for running it and a database to contain the data. </p> <p> The backend dev uses computer programmes to ensure that the server, the application and the database run smoothly together. This type of dev need to analyse what a company’s needs are and provide efficient programming solutions. To do all this amazing stuff they use a variety of server-side languages, like PHP, Ruby, Python and Java. </p> <ul> <li>Canada</li> <li>Unites States</li> <li>Australia</li> <li>Brazil</li> </ul> <table> <thead> <tr> <th>S. No.</th> <th>Name</th> <th>Title</th> </tr> </thead> <tbody> <tr> <td>20107</td> <td>Akshat Mittal</td> <td>MERN Stack Developer</td> </tr> <tr> <td>20106</td> <td>Akshat Khosya</td> <td>MERN Stack Developer</td> </tr> </tbody> </table>`,
		cover: "https://wallpaperaccess.com/full/1657789.jpg",
		color: "#4e8bd2",
		time: new Date(2018, 11, 24, 10, 33, 30),
	},
	{
		id: "akcbjkabf2b312b3ib",
		title: "Techsnap Blog",
		about: "This is a sample blog for the startup Techsnap",
		content: `<p> Front-end developers must keep in mind that the tools and skills used to create the front end of a website are always changing. So developers need to constantly learn and brush up skills in these areas to advance their careers </p> <section> <h2>HTML</h2> <p> HyperText Markup Language, or HTML, is the key structural component of all websites on the Internet. Web pages cannot exist without HTML. </p> <ul> <li>Web Design</li> <li>Responsive</li> <li>Webpage Graphics</li> <li>HTML elements</li> <li>HTML attributes</li> <li>Start Tags</li> <li>End Tags</li> <li>Element Content</li> <li> HTML Headings, Paragraphs, Links, Images, Buttons, Tables, and Lists </li> </ul> <img src="https://akshatmittal61.github.io/techsnap-blog/images/html5.webp" alt="HTML5" /> </section> <section> <h2>CSS</h2> <p> CSS stands for Cascading Style Sheets. CSS and HTML work together: CSS adds style to HTML. I like to use the analogy that HTML is like a face, and CSS is like the makeup. </p> <blockquote> <cite>CSS is the makeup for HTML.</cite> </blockquote> <p> Although CSS isn’t necessary to get a website online, basically every site online uses some kind of styling. Otherwise, it’d be pretty boring. With the most recent versions of CSS, you can do things like animations and more advanced styling that in the past was only possible with JavaScript or Flash. </p> <ul> <li>SS Syntax</li> <li>Selector Block</li> <li>Declaration Block</li> <li>Precompilers/Preprocessors</li> <li>DRY (Don’t Repeat Yourself)</li> <li>Sass</li> <li>Less</li> <li>Styles</li> <li>CSS Frameworks</li> <li>Bootstrap</li> <li>Foundation</li> <li>Responsive Design</li> </ul> </section> <section> <h2>Javscript</h2> <p> JavaScript, or JS, has been advancing rapidly over the years. It has many purposes nowadays and can be used on the front or back end. </p> <p> In relation to front-end development, JS is important because it helps make web pages interactive. You can do awesome things like create polls, quizzes or form submissions. Nowadays there are numerous JS libraries online to help you take your web pages to the next level. </p> <code> <span>const i=1;</span> <span> console.log(i); </span> <br /> <span> let arr=[5,6,7] </span> <span> arr.forEach(item=&gt; </span> <span> &nbsp; console.log(item+5); </span> <span> ) </span> </code> <code> <span> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illo unde, facilis tenetur assumenda quia eligendi beatae ea repudiandae laborum nobis, placeat adipisci ab quos ipsum odit sed provident dolores temporibus! </span> </code> </section>`,
		cover: "https://akshatmittal61.github.io/techsnap-blog/images/1.png",
		color: "#ff99ef",
		time: new Date(2016, 4, 22, 11, 52, 44),
	},
];
export default diaries;
